spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/germanapp
    username: postgres
    password: 1234asd.
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
