services:
  postgres:
    image: postgres:15
    container_name: german-postgres
    environment:
      POSTGRES_DB: germanapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234asd.
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
